### ISSUE TITLE
Custom dirlist not working

### ISSUE THREAD

**Issue by victorshx** [SharonBrizinov/s3viewer#1]
This tool is really great, nonetheless, with the built-in downloader. I couldn't get it to work with an S3 compatible endpoint hence I looked into the code to find how you generate the dirlist.

Here is what I got: `aws --no-sign-request s3 ls s3://capitol-hill-riots --endpoint-url=https://s3.us-east-1.wasabisys.com --recursive > list.txt`

Here is the preview:
![image](https://user-images.githubusercontent.com/34960876/104134399-343c6200-53c4-11eb-83b4-c886c96093ee.png)

However, I get a warning message box when trying to load it.
![image](https://user-images.githubusercontent.com/34960876/104134422-5f26b600-53c4-11eb-95e9-a172ef393d97.png)

**Comment by victorshx** [comment]
PS: Here is the attached file should you need it for debugging.

[list.txt](https://github.com/SharonBrizinov/s3viewer/files/5793255/list.txt)

**Comment by SharonBrizinov** [comment]
Hi,

I looked at your data and I think that your shell is not configured to work with utf-8 because when I generated the dirlist everything was fine. Can you try to generate the dirlist from a different machine?

Please look at the comparison I made between your dirlist and mine. I've also attached the new dirlist I created.

[list2.txt](https://github.com/SharonBrizinov/s3viewer/files/5793345/list2.txt)
<img width="1611" alt="compare" src="https://user-images.githubusercontent.com/519424/104135983-0511fa80-539c-11eb-8898-f4f83f90027c.png">

**Comment by victorshx** [comment]
Unfortunately, I do not have a Linux machine. I've also enabled the beta UTF-8 support.
![image](https://user-images.githubusercontent.com/34960876/104151520-2d3f3f00-5418-11eb-81a2-9c9e6b733ee3.png)

However, it's still showing the same error with a slightly different message.
![image](https://user-images.githubusercontent.com/34960876/104151890-15b48600-5419-11eb-82c8-58395867defb.png)

But I tried loading your dirlist and it works fine on my machine! Can I confirm that you are on a Linux machine?

**Comment by SharonBrizinov** [comment]
can you upload the new dirlist?

**Comment by victorshx** [comment]
> can you upload the new dirlist?

Here [list.txt](https://github.com/SharonBrizinov/s3viewer/files/5794459/list.txt)

**Comment by SharonBrizinov** [comment]
I've pushed a fix to support different encoding schemes
so now even the first dirlist should work for you.

Can you try again? (if you want to wait for the binary it will be ready in a few min)

**Comment by victorshx** [comment]
The latest commit works for the first dirlist, and the latest dirlist 👍 

![image](https://user-images.githubusercontent.com/34960876/104158686-d2faaa00-5428-11eb-883f-e6216986f105.png)
